### ISSUE TITLE
Use a location for HSQLDB data files outside of /opt/pivotal/spring-xd

### ISSUE THREAD

**Issue by trisberg** [spring-projects/spring-xd-ambari#12]
Currently the data files for HSQLDB end up under  `/opt/pivotal/spring-xd/xd/data/job` which is not great when we update the software version. We should use a different location, maybe `/var/spring-xd/data/job`.

**Comment by jvalkeal** [comment]
I can see that `HSQLServerBean` can use properties and possibly change data path, but where is that default path set and what property I need to set to change it?
