### ISSUE TITLE
Move XD module config location to shared location and use properties for customization

### ISSUE THREAD

**Issue by trisberg** [spring-projects/spring-xd-ambari#13]
Right now we have the "XD config location" set to `/etc/springxd/conf/`. 

The XD module config location uses "file:/opt/pivotal/spring-xd/xd/config/modules/" which is not ideal. How do we expect users to modify the module config options? This should be possible through custom properties.

**Comment by jvalkeal** [comment]
Yeah, I'll create a new template for `modules.yml`. Will then work same way than setting additional properties for `servers.yml`.
