### ISSUE TITLE
Add support for namenode HA

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-xd-ambari#6]
Ok, so, if HA is enabled a custom configuration is needed. HA is silently handled by a hadoop dfs client but configuration is still needed. We don't have any custom tweaks in SHDP for this but we just need to write a different xd container/shell config depending if HA is enabled.

**Comment by ysung-pivotal** [comment]
In hadoop.properties.j2
This line:
dfs.client.failover.proxy.provider.mycluster=org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider

Should be:
dfs.client.failover.proxy.provider.{{dfs_ha_nameservices}}=org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider

**Comment by jvalkeal** [comment]
should be fixed now, closing.
